# Generated by Django 5.0.7 on 2024-08-02 21:46

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mainapp", "0002_cashapps_games_cashouts_gameloads"),
    ]

    operations = [
        migrations.AddField(
            model_name="cashapps",
            name="verification_date",
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
