# Generated by Django 5.0.7 on 2024-08-21 08:10

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mainapp", "0005_alter_users_salary_alter_users_shift_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="gameloads",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
