# Generated by Django 5.0.7 on 2024-08-22 15:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mainapp", "0007_pagepairs"),
    ]

    operations = [
        migrations.CreateModel(
            name="Redeem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("datetime", models.DateTimeField(auto_now_add=True)),
                ("amount", models.IntegerField()),
                ("bonus", models.IntegerField(default=0)),
                ("customer", models.CharField(max_length=100)),
                ("signup", models.BooleanField(default=False)),
                (
                    "agent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="mainapp.games"
                    ),
                ),
            ],
        ),
    ]
