# Generated by Django 5.0.7 on 2024-08-22 15:38

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mainapp", "0008_redeem"),
    ]

    operations = [
        migrations.AddField(
            model_name="redeem",
            name="page",
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
    ]
