# Generated by Django 5.0.7 on 2024-08-22 15:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("mainapp", "0009_redeem_page"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Redeem",
            new_name="Deposit",
        ),
    ]
