# Generated by Django 5.0.7 on 2024-08-23 06:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mainapp", "0011_redeems"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cashapps",
            name="cash_tag",
            field=models.CharField(max_length=50),
        ),
    ]
