# Generated by Django 5.0.7 on 2024-08-23 09:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mainapp", "0012_alter_cashapps_cash_tag"),
    ]

    operations = [
        migrations.AddField(
            model_name="redeems",
            name="agent",
            field=models.ForeignKey(
                default=5,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="redeems",
            name="cashtag_uuid",
            field=models.CharField(max_length=50),
        ),
    ]
