# Generated by Django 5.0.7 on 2024-08-28 04:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("mainapp", "0014_cashapps_activity_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cashapps",
            name="activity_status",
        ),
    ]
