# Generated by Django 5.0.7 on 2024-08-28 05:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("mainapp", "0015_remove_cashapps_activity_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="redeems",
            name="player_name",
        ),
    ]
