# Generated by Django 5.1 on 2024-09-12 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0018_deposit_cashtag_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashapps',
            name='balance',
            field=models.IntegerField(default=0),
        ),
    ]
