# Generated by Django 5.1 on 2024-09-13 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0019_cashapps_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='redeems',
            name='cashtag_uuid',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
