# Generated by Django 5.1 on 2024-09-13 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0020_alter_redeems_cashtag_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='redeems',
            name='customer_cashtag',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
